CREATE TABLE IF NOT EXISTS "user" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre de usuario
    "username" VARCHAR(50) NOT NULL UNIQUE,
    -- Contrasenia almacenada de forma segura
    "password_hash" VARCHAR(255) NOT NULL,
    -- Nombre
    "first_name" VARCHAR(100) NOT NULL,
    -- Apellido Paterno
    "paternal_last_name" VARCHAR(100) NOT NULL,
    -- Apellido Materno
    "maternal_last_name" VARCHAR(100) NOT NULL,
    -- Estado del usuario
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'ACTIVE',
            'INACTIVE',
            'BLOCKED'
        )
    ),
    -- Fecha de creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Ultima modificacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "role" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre del rol
    "name" VARCHAR(50) NOT NULL UNIQUE,
    -- Descripcion
    "description" VARCHAR(255),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "permission" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre del permiso
    "name" VARCHAR(100) NOT NULL UNIQUE,
    -- Descripcion
    "description" VARCHAR(255),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_role" (
    -- Usuario
    "user_id" BIGINT NOT NULL,
    -- Rol
    "role_id" BIGINT NOT NULL,
    PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE IF NOT EXISTS "role_permission" (
    -- Rol
    "role_id" BIGINT NOT NULL,
    -- Permiso
    "permission_id" BIGINT NOT NULL,
    PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE IF NOT EXISTS "customer" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre
    "first_name" VARCHAR(100) NOT NULL,
    -- Apellido Paterno
    "paternal_last_name" VARCHAR(100),
    -- Apellido Materno
    "maternal_last_name" VARCHAR(100),
    -- Telefono
    "phone" VARCHAR(20),
    -- Correo Electronic
    "email" VARCHAR(254),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    -- Fecha de registro
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Ultima modificacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "fiscal_data" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Cliente
    "customer_id" BIGINT NOT NULL,
    -- Identificador fiscal
    "tax_id" VARCHAR(20) NOT NULL,
    -- Nombre o razon social fiscal
    "legal_name" VARCHAR(255) NOT NULL,
    -- Regimen Fiscal
    "tax_regime" VARCHAR(10) NOT NULL,
    -- Codigo Postal Fiscal
    "postal_code" VARCHAR(5) NOT NULL,
    -- Uso Fiscal
    "fiscal_use" VARCHAR(10) NOT NULL,
    -- Fecha de creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Ultima Modificacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "category" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre
    "name" VARCHAR(100) NOT NULL UNIQUE,
    -- Descripcion
    "description" VARCHAR(255),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "brand" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre de Marca
    "name" VARCHAR(100) NOT NULL UNIQUE,
    -- Descripcion
    "description" VARCHAR(255),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "product" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Codigo Interno
    "sku" VARCHAR(50) NOT NULL UNIQUE,
    -- Codigo de Barras
    "barcode" VARCHAR(50) UNIQUE,
    -- Nombre
    "name" VARCHAR(150) NOT NULL,
    -- Descripcion
    "description" TEXT,
    -- Categoria
    "category_id" BIGINT NOT NULL,
    -- Marca
    "brand_id" BIGINT,
    -- Precio de Venta
    "sale_price" DECIMAL(12, 2) NOT NULL CHECK (sale_price >= 0),
    -- Costo
    "cost_price" DECIMAL(12, 2) NOT NULL CHECK (cost_price >= 0),
    -- Nivel de Alerta
    "stock_alert_level" INTEGER NOT NULL CHECK (stock_alert_level >= 0),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Actualizacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "discount" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre
    "name" VARCHAR(100) NOT NULL,
    -- Tipo
    "type" VARCHAR(30) NOT NULL CHECK (
        type IN ('PERCENTAGE', 'FIXED_AMOUNT')
    ),
    -- Valor
    "value" DECIMAL(12, 2) NOT NULL CHECK (value >= 0),
    -- Condiciones
    "conditions" JSONB,
    -- Inicio
    "starts_at" TIMESTAMP NOT NULL,
    -- Fin
    "ends_at" TIMESTAMP,
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Actualizacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id"),
    CHECK (
        ends_at IS NULL
        OR ends_at > starts_at
    ),
    CHECK (
        (
            type = 'PERCENTAGE'
            AND value BETWEEN 0 AND 100
        )
        OR (
            type = 'FIXED_AMOUNT'
            AND value >= 0
        )
    )
);

CREATE TABLE IF NOT EXISTS "service" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre
    "name" VARCHAR(100) NOT NULL,
    -- Descripcion
    "description" TEXT,
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Actualizacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "service_rate" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Servicio
    "service_id" BIGINT NOT NULL,
    -- Nombre de tarifa
    "name" VARCHAR(100) NOT NULL,
    -- Precio Unitario
    "unit_price" DECIMAL(12, 2) NOT NULL CHECK (unit_price >= 0),
    -- Configuracion adicional
    "configuration" JSONB,
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Actualizacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "inventory" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Producto
    "product_id" BIGINT NOT NULL UNIQUE,
    -- Existencia
    "quantity" INTEGER NOT NULL CHECK (quantity >= 0),
    -- Cantidad Apartada
    "reserved_quantity" INTEGER NOT NULL CHECK (
        reserved_quantity >= 0
        AND reserved_quantity <= quantity
    ),
    -- Actualizacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "inventory_movement" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Producto
    "product_id" BIGINT NOT NULL,
    -- Tipo de Movimiento
    "type" VARCHAR(30) NOT NULL CHECK (
        type IN (
            'PURCHASE',
            'SALE',
            'ADJUSTMENT',
            'RETURN',
            'RESERVE',
            'RELEASE'
        )
    ),
    -- Cantidad
    "quantity" INTEGER NOT NULL CHECK (quantity > 0),
    -- Tipo de Referencia
    "reference_type" VARCHAR(30),
    -- Identificador de referencia
    "reference_id" BIGINT,
    -- Usuario Responsable
    "user_id" BIGINT NOT NULL,
    -- Motivo
    "reason" VARCHAR(255),
    -- Notas
    "notes" TEXT,
    -- Fecha
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "inventory_incident" (
    -- Identificador
    -- 
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Producto
    "product_id" BIGINT NOT NULL,
    -- Cantidad Registrada
    "system_quantity" INTEGER NOT NULL CHECK (system_quantity >= 0),
    -- Cantidad Fisica
    "physical_quantity" INTEGER NOT NULL CHECK (physical_quantity >= 0),
    -- Diferencia
    "difference" INTEGER NOT NULL,
    -- Motivo
    "reason" VARCHAR(255) NOT NULL,
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'PENDING',
            'IN_REVIEW',
            'RESOLVED',
            'REJECTED',
            'CANCELLED'
        )
    ),
    -- Usuario que reporta
    "reported_by" BIGINT NOT NULL,
    -- Usuario que resuelve
    "resolved_by" BIGINT,
    -- Notas
    "notes" TEXT,
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Resolucion
    "resolved_at" TIMESTAMP,
    PRIMARY KEY ("id"),
    CHECK (
        difference = physical_quantity - system_quantity
    )
);

CREATE TABLE IF NOT EXISTS "sale" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Cliente
    "customer_id" BIGINT,
    -- Cajero
    "user_id" BIGINT NOT NULL,
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'PENDING',
            'COMPLETED',
            'CANCELLED',
            'REFUNDED'
        )
    ),
    -- Subtotal
    "subtotal" DECIMAL(12, 2) NOT NULL CHECK (subtotal >= 0),
    -- Descuento Total
    "discount_total" DECIMAL(12, 2) NOT NULL CHECK (discount_total >= 0),
    -- Impuestos
    "tax_total" DECIMAL(12, 2) NOT NULL CHECK (tax_total >= 0),
    -- Total
    "total" DECIMAL(12, 2) NOT NULL CHECK (total >= 0),
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Finalizacion
    "completed_at" TIMESTAMP,
    -- Cancelacion
    "cancelled_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "sale_item" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Venta
    "sale_id" BIGINT NOT NULL,
    -- Producto
    "product_id" BIGINT,
    -- Servicio
    "service_id" BIGINT,
    -- Descripción historica
    "description" VARCHAR(255) NOT NULL,
    -- Cantidad
    "quantity" DECIMAL(12, 3) NOT NULL CHECK (quantity > 0),
    -- Precio Historico
    "unit_price" DECIMAL(12, 2) NOT NULL CHECK (unit_price >= 0),
    -- Descuento
    "discount_id" BIGINT,
    -- Tipo Aplicado
    "discount_type" VARCHAR(30),
    -- Valor Aplicado
    "discount_value" DECIMAL(12, 2) CHECK (discount_value >= 0),
    -- Monto Descontado
    "discount_amount" DECIMAL(12, 2) NOT NULL CHECK (discount_amount >= 0),
    -- Impuesto
    "tax" DECIMAL(12, 2) NOT NULL CHECK (tax >= 0),
    -- Subtotal
    "subtotal" DECIMAL(12, 2) NOT NULL CHECK (subtotal >= 0),
    PRIMARY KEY ("id"),
    CHECK (
        (
            product_id IS NOT NULL
            AND service_id IS NULL
        )
        OR (
            product_id IS NULL
            AND service_id IS NOT NULL
        )
    ),
    CHECK (
        discount_type IS NULL
        OR discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')
    ),
    CHECK (
        (
            discount_type IS NULL
            AND discount_value IS NULL
        )
        OR (
            discount_type IS NOT NULL
            AND discount_value IS NOT NULL
        )
    ),
    CHECK (
        discount_type IS NULL
        OR (
            discount_type = 'PERCENTAGE'
            AND discount_value BETWEEN 0 AND 100
        )
        OR (
            discount_type = 'FIXED_AMOUNT'
            AND discount_value >= 0
        )
    )
);

CREATE TABLE IF NOT EXISTS "payment_method" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre
    "name" VARCHAR(50) NOT NULL UNIQUE,
    -- Tipo
    "type" VARCHAR(30) NOT NULL CHECK (
        type IN (
            'CASH',
            'CARD',
            'TRANSFER',
            'DIGITAL_WALLET',
            'OTHER'
        )
    ),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "payment" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Venta
    "sale_id" BIGINT NOT NULL,
    -- Metodo
    "payment_method_id" BIGINT NOT NULL,
    -- Monto
    "amount" DECIMAL(12, 2) NOT NULL CHECK (amount > 0),
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'COMPLETED',
            'PENDING',
            'FAILED',
            'REFUNDED'
        )
    ),
    -- Referencia Externa
    "reference" VARCHAR(100),
    -- Usuario
    "user_id" BIGINT NOT NULL,
    -- Fecha
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ticket" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Venta
    "sale_id" BIGINT NOT NULL UNIQUE,
    -- Numero
    "ticket_number" VARCHAR(50) NOT NULL UNIQUE,
    -- Fecha de Emision
    "issued_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "return" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Venta original
    "sale_id" BIGINT NOT NULL,
    -- Usuario Responsable
    "user_id" BIGINT NOT NULL,
    -- Tipo
    "type" VARCHAR(30) NOT NULL CHECK (type IN ('TOTAL', 'PARTIAL')),
    -- Motivo
    "reason" TEXT NOT NULL,
    -- Total
    "total" DECIMAL(12, 2) NOT NULL CHECK (total >= 0),
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'PENDING',
            'APPROVED',
            'REJECTED',
            'COMPLETED',
            'CANCELLED'
        )
    ),
    -- Fecha
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "return_item" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Devolucion
    "return_id" BIGINT NOT NULL,
    -- Detalle Vendido
    "sale_item_id" BIGINT NOT NULL,
    -- Cantidad
    "quantity" DECIMAL(12, 3) NOT NULL CHECK (quantity > 0),
    -- Monto
    "amount" DECIMAL(12, 2) NOT NULL CHECK (amount >= 0),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "reservation" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Cliente
    "customer_id" BIGINT NOT NULL,
    -- Usuario
    "user_id" BIGINT NOT NULL,
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'ACTIVE',
            'COMPLETED',
            'CANCELLED',
            'EXPIRED'
        )
    ),
    -- Total
    "total" DECIMAL(12, 2) NOT NULL CHECK (total >= 0),
    -- Pagado
    "paid_amount" DECIMAL(12, 2) NOT NULL CHECK (paid_amount >= 0),
    -- Pendiente
    "due_amount" DECIMAL(12, 2) NOT NULL CHECK (due_amount >= 0),
    -- Anticipo Aplicado
    "minimum_percentage_applied" DECIMAL(5, 2) NOT NULL CHECK (
        minimum_percentage_applied BETWEEN 0 AND 100
    ),
    -- Retencion por Cancelacion
    "cancellation_retention_percentage_applied" DECIMAL(5, 2) NOT NULL CHECK (
        cancellation_retention_percentage_applied BETWEEN 0 AND 100
    ),
    -- Retencion por vencimiento
    "expiration_retention_percentage_applied" DECIMAL(5, 2) NOT NULL CHECK (
        expiration_retention_percentage_applied BETWEEN 0 AND 100
    ),
    -- Creacion
    "reserved_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Vencimiento
    "expires_at" TIMESTAMP NOT NULL,
    -- Liquidacion
    "completed_at" TIMESTAMP,
    -- Cancelacion
    "cancelled_at" TIMESTAMP,
    PRIMARY KEY ("id"),
    CHECK (
        paid_amount >= 0
        AND paid_amount <= total
    ),
    CHECK (
        due_amount = total - paid_amount
    ),
    CHECK (expires_at > reserved_at)
);

CREATE TABLE IF NOT EXISTS "reservation_item" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Apartado
    "reservation_id" BIGINT NOT NULL,
    -- Producto
    "product_id" BIGINT NOT NULL,
    -- Cantidad
    "quantity" INTEGER NOT NULL CHECK (quantity > 0),
    -- Precio Historico
    "unit_price" DECIMAL(12, 2) NOT NULL CHECK (unit_price >= 0),
    -- Subtotal
    "subtotal" DECIMAL(12, 2) NOT NULL CHECK (subtotal >= 0),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "reservation_payment" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Apartado
    "reservation_id" BIGINT NOT NULL,
    -- Metodo de pago
    "payment_method_id" BIGINT NOT NULL,
    -- Monto
    "amount" DECIMAL(12, 2) NOT NULL CHECK (amount > 0),
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'CONFIRMED',
            'CANCELLED',
            'REFUNDED'
        )
    ),
    -- Referencia
    "reference" VARCHAR(100),
    -- Usuario
    "user_id" BIGINT NOT NULL,
    -- Fecha
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "reservation_configuration" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Anticipo Minimo
    "minimum_percentage" DECIMAL(5, 2) NOT NULL CHECK (
        minimum_percentage BETWEEN 0 AND 100
    ),
    -- Dias de Vigencia
    "expiration_days" INTEGER NOT NULL CHECK (expiration_days > 0),
    -- Retencion por cancelacion
    "cancellation_retention_percentage" DECIMAL(5, 2) NOT NULL CHECK (
        cancellation_retention_percentage BETWEEN 0 AND 100
    ),
    -- Retencion por vencimiento
    "expiration_retention_percentage" DECIMAL(5, 2) NOT NULL CHECK (
        expiration_retention_percentage BETWEEN 0 AND 100
    ),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Actualizacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

-- Índice único para permitir solo una configuración activa
CREATE UNIQUE INDEX uq_active_reservation_configuration ON reservation_configuration (active)
WHERE
    active = TRUE;

CREATE TABLE IF NOT EXISTS "supplier" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Nombre
    "name" VARCHAR(150) NOT NULL,
    -- Telefono
    "phone" VARCHAR(20),
    -- Correo
    "email" VARCHAR(254),
    -- Direccion
    "address" VARCHAR(255),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Actualizacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "product_supplier" (
    -- Producto
    "product_id" BIGINT NOT NULL,
    -- Proveedor
    "supplier_id" BIGINT NOT NULL,
    -- Codigo del proveedor
    "supplier_code" VARCHAR(50),
    -- Ultimo Costo Conocido
    "last_purchase_price" DECIMAL(12, 2) CHECK (last_purchase_price >= 0),
    -- Estado
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY ("product_id", "supplier_id")
);

CREATE TABLE IF NOT EXISTS "purchase" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Proveedor
    "supplier_id" BIGINT NOT NULL,
    -- Usuario Responsable
    "user_id" BIGINT NOT NULL,
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'DRAFT',
            'ORDERED',
            'PARTIALLY_RECEIVED',
            'RECEIVED',
            'CANCELLED'
        )
    ),
    -- Subtotal
    "subtotal" DECIMAL(12, 2) NOT NULL CHECK (subtotal >= 0),
    -- Total
    "total" DECIMAL(12, 2) NOT NULL CHECK (total >= 0),
    -- Notas
    "notes" TEXT,
    -- Fecha Pedido
    "ordered_at" TIMESTAMP,
    -- Fecha Recepcion
    "received_at" TIMESTAMP,
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "purchase_item" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Compra
    "purchase_id" BIGINT NOT NULL,
    -- Producto
    "product_id" BIGINT NOT NULL,
    -- Cantidad Solicitada
    "quantity_ordered" INTEGER NOT NULL CHECK (quantity_ordered > 0),
    -- Cantidad Recibida
    "quantity_received" INTEGER NOT NULL CHECK (quantity_received >= 0),
    -- Costo Unitario
    "unit_cost" DECIMAL(12, 2) NOT NULL CHECK (unit_cost >= 0),
    -- Subtotal
    "subtotal" DECIMAL(12, 2) NOT NULL CHECK (subtotal >= 0),
    -- Notas
    "notes" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "purchase_incident" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Compra
    "purchase_id" BIGINT NOT NULL,
    -- Detalle
    "purchase_item_id" BIGINT NOT NULL,
    -- Tipo
    "type" VARCHAR(30) NOT NULL CHECK (
        type IN (
            'DAMAGED',
            'MISSING',
            'WRONG_PRODUCT',
            'EXPIRED',
            'OVERAGE'
        )
    ),
    -- Cantidad afectada
    "quantity" INTEGER NOT NULL CHECK (quantity > 0),
    -- Descripcion
    "description" TEXT NOT NULL,
    -- Resolucion
    "resolution" VARCHAR(255),
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'PENDING',
            'IN_REVIEW',
            'RESOLVED',
            'REJECTED'
        )
    ),
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Resolucion
    "resolved_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "cash_register" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Usuario
    "user_id" BIGINT NOT NULL,
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'CLOSED')),
    -- Monto Inicial
    "opening_amount" DECIMAL(12, 2) NOT NULL CHECK (opening_amount >= 0),
    -- Apertura
    "opened_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Cierre
    "closed_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Restricción: solo una caja abierta por usuario
CREATE UNIQUE INDEX uq_user_open_cash_register ON cash_register (user_id)
WHERE
    status = 'OPEN';

CREATE TABLE IF NOT EXISTS "cash_movement" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Caja
    "cash_register_id" BIGINT NOT NULL,
    -- Tipo
    "type" VARCHAR(30) NOT NULL CHECK (type IN ('INCOME', 'EXPENSE')),
    -- Monto
    "amount" DECIMAL(12, 2) NOT NULL CHECK (amount > 0),
    -- Tipo de referencia
    "reference_type" VARCHAR(30),
    -- Referencia
    "reference_id" BIGINT,
    -- Usuario
    "user_id" BIGINT NOT NULL,
    -- Descripcion
    "description" TEXT,
    -- Fecha
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "cash_closing" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Caja
    "cash_register_id" BIGINT NOT NULL,
    -- Usuario
    "user_id" BIGINT NOT NULL,
    -- Monto esperado
    "expected_amount" DECIMAL(12, 2) NOT NULL CHECK (expected_amount >= 0),
    -- Monto contado
    "actual_amount" DECIMAL(12, 2) NOT NULL CHECK (actual_amount >= 0),
    -- Diferencia
    "difference" DECIMAL(12, 2) NOT NULL,
    -- Observaciones
    "observations" TEXT,
    -- Fecha
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id"),
    CHECK (
        difference = actual_amount - expected_amount
    )
);

CREATE TABLE IF NOT EXISTS "invoice" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Venta
    "sale_id" BIGINT NOT NULL UNIQUE,
    -- Datos Fiscales
    "fiscal_data_id" BIGINT NOT NULL,
    -- Proveedor
    "provider" VARCHAR(50) NOT NULL,
    -- Identificador Externo
    "external_id" VARCHAR(100),
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'PENDING',
            'ISSUED',
            'FAILED',
            'CANCELLED'
        )
    ),
    -- Fecha de emicion
    "issued_at" TIMESTAMP,
    -- Error
    "error_message" TEXT,
    -- Creacion
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Actualizacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "product_interest" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Cliente
    "customer_id" BIGINT,
    -- Producto
    "product_id" BIGINT,
    -- Nombre solicitado
    "requested_name" VARCHAR(150) NOT NULL,
    -- Notas
    "notes" TEXT,
    -- Estado
    "status" VARCHAR(20) NOT NULL CHECK (
        status IN (
            'PENDING',
            'IN_REVIEW',
            'APPROVED',
            'REJECTED',
            'COMPLETED'
        )
    ),
    -- Fecha
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "business_configuration" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Clave
    "key" VARCHAR(100) NOT NULL UNIQUE,
    -- Valor
    "value" TEXT NOT NULL,
    -- Tipo de dato
    "data_type" VARCHAR(20) NOT NULL CHECK (
        data_type IN (
            'STRING',
            'INTEGER',
            'DECIMAL',
            'BOOLEAN',
            'TIME',
            'DATE',
            'DATETIME',
            'JSON'
        )
    ),
    -- Descripcion
    "description" VARCHAR(255),
    -- Usuario
    "updated_by" BIGINT NOT NULL,
    -- Actualizacion
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "audit_record" (
    -- Identificador
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Usuario Responsable
    "user_id" BIGINT NOT NULL,
    -- Accion
    "action" VARCHAR(30) NOT NULL CHECK (
        action IN (
            'CREATE',
            'UPDATE',
            'DELETE',
            'RESTORE',
            'LOGIN',
            'LOGOUT'
        )
    ),
    -- Tipo de Entidad
    "entity_type" VARCHAR(50) NOT NULL,
    -- Registro Afectado
    "entity_id" BIGINT NOT NULL,
    -- Valor Anterior
    "old_value" JSONB,
    -- Valor Nuevo
    "new_value" JSONB,
    -- Motivo
    "reason" TEXT,
    -- Fecha
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);


COMMENT ON COLUMN "user"."id" IS 'Identificador';

COMMENT ON COLUMN "user"."username" IS 'Nombre de usuario';

COMMENT ON COLUMN "user"."password_hash" IS 'Contrasenia almacenada de forma segura';

COMMENT ON COLUMN "user"."first_name" IS 'Nombre';

COMMENT ON COLUMN "user"."paternal_last_name" IS 'Apellido Paterno';

COMMENT ON COLUMN "user"."maternal_last_name" IS 'Apellido Materno';

COMMENT ON COLUMN "user"."status" IS 'Estado del usuario';

COMMENT ON COLUMN "user"."created_at" IS 'Fecha de creacion';

COMMENT ON COLUMN "user"."updated_at" IS 'Ultima modificacion';

COMMENT ON COLUMN "role"."id" IS 'Identificador';

COMMENT ON COLUMN "role"."name" IS 'Nombre del rol';

COMMENT ON COLUMN "role"."description" IS 'Descripcion';

COMMENT ON COLUMN "role"."active" IS 'Estado';

COMMENT ON COLUMN "permission"."id" IS 'Identificador';

COMMENT ON COLUMN "permission"."name" IS 'Nombre del permiso';

COMMENT ON COLUMN "permission"."description" IS 'Descripcion';

COMMENT ON COLUMN "permission"."active" IS 'Estado';

COMMENT ON COLUMN "user_role"."user_id" IS 'Usuario';

COMMENT ON COLUMN "user_role"."role_id" IS 'Rol';

COMMENT ON COLUMN "role_permission"."role_id" IS 'Rol';

COMMENT ON COLUMN "role_permission"."permission_id" IS 'Permiso';

COMMENT ON COLUMN "customer"."id" IS 'Identificador';

COMMENT ON COLUMN "customer"."first_name" IS 'Nombre';

COMMENT ON COLUMN "customer"."paternal_last_name" IS 'Apellido Paterno';

COMMENT ON COLUMN "customer"."maternal_last_name" IS 'Apellido Materno';

COMMENT ON COLUMN "customer"."phone" IS 'Telefono';

COMMENT ON COLUMN "customer"."email" IS 'Correo Electronic';

COMMENT ON COLUMN "customer"."active" IS 'Estado';

COMMENT ON COLUMN "customer"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "customer"."updated_at" IS 'Ultima modificacion';

COMMENT ON COLUMN "fiscal_data"."id" IS 'Identificador';

COMMENT ON COLUMN "fiscal_data"."customer_id" IS 'Cliente';

COMMENT ON COLUMN "fiscal_data"."tax_id" IS 'Identificador fiscal';

COMMENT ON COLUMN "fiscal_data"."legal_name" IS 'Nombre o razon social fiscal';

COMMENT ON COLUMN "fiscal_data"."tax_regime" IS 'Regimen Fiscal';

COMMENT ON COLUMN "fiscal_data"."postal_code" IS 'Codigo Postal Fiscal';

COMMENT ON COLUMN "fiscal_data"."fiscal_use" IS 'Uso Fiscal';

COMMENT ON COLUMN "fiscal_data"."created_at" IS 'Fecha de creacion';

COMMENT ON COLUMN "fiscal_data"."updated_at" IS 'Ultima Modificacion';

COMMENT ON COLUMN "category"."id" IS 'Identificador';

COMMENT ON COLUMN "category"."name" IS 'Nombre';

COMMENT ON COLUMN "category"."description" IS 'Descripcion';

COMMENT ON COLUMN "category"."active" IS 'Estado';

COMMENT ON COLUMN "brand"."id" IS 'Identificador';

COMMENT ON COLUMN "brand"."name" IS 'Nombre de Marca';

COMMENT ON COLUMN "brand"."description" IS 'Descripcion';

COMMENT ON COLUMN "brand"."active" IS 'Estado';

COMMENT ON COLUMN "product"."id" IS 'Identificador';

COMMENT ON COLUMN "product"."sku" IS 'Codigo Interno';

COMMENT ON COLUMN "product"."barcode" IS 'Codigo de Barras';

COMMENT ON COLUMN "product"."name" IS 'Nombre';

COMMENT ON COLUMN "product"."description" IS 'Descripcion';

COMMENT ON COLUMN "product"."category_id" IS 'Categoria';

COMMENT ON COLUMN "product"."brand_id" IS 'Marca';

COMMENT ON COLUMN "product"."sale_price" IS 'Precio de Venta';

COMMENT ON COLUMN "product"."cost_price" IS 'Costo';

COMMENT ON COLUMN "product"."stock_alert_level" IS 'Nivel de Alerta';

COMMENT ON COLUMN "product"."active" IS 'Estado';

COMMENT ON COLUMN "product"."created_at" IS 'Creacion';

COMMENT ON COLUMN "product"."updated_at" IS 'Actualizacion';

COMMENT ON COLUMN "discount"."id" IS 'Identificador';

COMMENT ON COLUMN "discount"."name" IS 'Nombre';

COMMENT ON COLUMN "discount"."type" IS 'Tipo';

COMMENT ON COLUMN "discount"."value" IS 'Valor';

COMMENT ON COLUMN "discount"."conditions" IS 'Condiciones';

COMMENT ON COLUMN "discount"."starts_at" IS 'Inicio';

COMMENT ON COLUMN "discount"."ends_at" IS 'Fin';

COMMENT ON COLUMN "discount"."active" IS 'Estado';

COMMENT ON COLUMN "discount"."created_at" IS 'Creacion';

COMMENT ON COLUMN "discount"."updated_at" IS 'Actualizacion';

COMMENT ON COLUMN "service"."id" IS 'Identificador';

COMMENT ON COLUMN "service"."name" IS 'Nombre';

COMMENT ON COLUMN "service"."description" IS 'Descripcion';

COMMENT ON COLUMN "service"."active" IS 'Estado';

COMMENT ON COLUMN "service"."created_at" IS 'Creacion';

COMMENT ON COLUMN "service"."updated_at" IS 'Actualizacion';

COMMENT ON COLUMN "service_rate"."id" IS 'Identificador';

COMMENT ON COLUMN "service_rate"."service_id" IS 'Servicio';

COMMENT ON COLUMN "service_rate"."name" IS 'Nombre de tarifa';

COMMENT ON COLUMN "service_rate"."unit_price" IS 'Precio Unitario';

COMMENT ON COLUMN "service_rate"."configuration" IS 'Configuracion adicional';

COMMENT ON COLUMN "service_rate"."active" IS 'Estado';

COMMENT ON COLUMN "service_rate"."created_at" IS 'Creacion';

COMMENT ON COLUMN "service_rate"."updated_at" IS 'Actualizacion';

COMMENT ON COLUMN "inventory"."id" IS 'Identificador';

COMMENT ON COLUMN "inventory"."product_id" IS 'Producto';

COMMENT ON COLUMN "inventory"."quantity" IS 'Existencia';

COMMENT ON COLUMN "inventory"."reserved_quantity" IS 'Cantidad Apartada';

COMMENT ON COLUMN "inventory"."updated_at" IS 'Actualizacion';

COMMENT ON COLUMN "inventory_movement"."id" IS 'Identificador';

COMMENT ON COLUMN "inventory_movement"."product_id" IS 'Producto';

COMMENT ON COLUMN "inventory_movement"."type" IS 'Tipo de Movimiento';

COMMENT ON COLUMN "inventory_movement"."quantity" IS 'Cantidad';

COMMENT ON COLUMN "inventory_movement"."reference_type" IS 'Tipo de Referencia';

COMMENT ON COLUMN "inventory_movement"."reference_id" IS 'Identificador de referencia';

COMMENT ON COLUMN "inventory_movement"."user_id" IS 'Usuario Responsable';

COMMENT ON COLUMN "inventory_movement"."reason" IS 'Motivo';

COMMENT ON COLUMN "inventory_movement"."notes" IS 'Notas';

COMMENT ON COLUMN "inventory_movement"."created_at" IS 'Fecha';

COMMENT ON COLUMN "inventory_incident"."id" IS 'Identificador ';

COMMENT ON COLUMN "inventory_incident"."product_id" IS 'Producto';

COMMENT ON COLUMN "inventory_incident"."system_quantity" IS 'Cantidad Registrada';

COMMENT ON COLUMN "inventory_incident"."physical_quantity" IS 'Cantidad Fisica';

COMMENT ON COLUMN "inventory_incident"."difference" IS 'Diferencia';

COMMENT ON COLUMN "inventory_incident"."reason" IS 'Motivo';

COMMENT ON COLUMN "inventory_incident"."status" IS 'Estado';

COMMENT ON COLUMN "inventory_incident"."reported_by" IS 'Usuario que reporta';

COMMENT ON COLUMN "inventory_incident"."resolved_by" IS 'Usuario que resuelve';

COMMENT ON COLUMN "inventory_incident"."notes" IS 'Notas';

COMMENT ON COLUMN "inventory_incident"."created_at" IS 'Creacion';

COMMENT ON COLUMN "inventory_incident"."resolved_at" IS 'Resolucion';

COMMENT ON COLUMN "sale"."id" IS 'Identificador';

COMMENT ON COLUMN "sale"."customer_id" IS 'Cliente';

COMMENT ON COLUMN "sale"."user_id" IS 'Cajero';

COMMENT ON COLUMN "sale"."status" IS 'Estado';

COMMENT ON COLUMN "sale"."subtotal" IS 'Subtotal';

COMMENT ON COLUMN "sale"."discount_total" IS 'Descuento Total';

COMMENT ON COLUMN "sale"."tax_total" IS 'Impuestos';

COMMENT ON COLUMN "sale"."total" IS 'Total';

COMMENT ON COLUMN "sale"."created_at" IS 'Creacion';

COMMENT ON COLUMN "sale"."completed_at" IS 'Finalizacion';

COMMENT ON COLUMN "sale"."cancelled_at" IS 'Cancelacion';

COMMENT ON COLUMN "sale_item"."id" IS 'Identificador';

COMMENT ON COLUMN "sale_item"."sale_id" IS 'Venta';

COMMENT ON COLUMN "sale_item"."product_id" IS 'Producto';

COMMENT ON COLUMN "sale_item"."service_id" IS 'Servicio';

COMMENT ON COLUMN "sale_item"."description" IS 'Descripción historica';

COMMENT ON COLUMN "sale_item"."quantity" IS 'Cantidad';

COMMENT ON COLUMN "sale_item"."unit_price" IS 'Precio Historico';

COMMENT ON COLUMN "sale_item"."discount_id" IS 'Descuento';

COMMENT ON COLUMN "sale_item"."discount_type" IS 'Tipo Aplicado';

COMMENT ON COLUMN "sale_item"."discount_value" IS 'Valor Aplicado';

COMMENT ON COLUMN "sale_item"."discount_amount" IS 'Monto Descontado';

COMMENT ON COLUMN "sale_item"."tax" IS 'Impuesto';

COMMENT ON COLUMN "sale_item"."subtotal" IS 'Subtotal';

COMMENT ON COLUMN "payment_method"."id" IS 'Identificador';

COMMENT ON COLUMN "payment_method"."name" IS 'Nombre';

COMMENT ON COLUMN "payment_method"."type" IS 'Tipo';

COMMENT ON COLUMN "payment_method"."active" IS 'Estado';

COMMENT ON COLUMN "payment"."id" IS 'Identificador';

COMMENT ON COLUMN "payment"."sale_id" IS 'Venta';

COMMENT ON COLUMN "payment"."payment_method_id" IS 'Metodo';

COMMENT ON COLUMN "payment"."amount" IS 'Monto';

COMMENT ON COLUMN "payment"."status" IS 'Estado';

COMMENT ON COLUMN "payment"."reference" IS 'Referencia Externa';

COMMENT ON COLUMN "payment"."user_id" IS 'Usuario';

COMMENT ON COLUMN "payment"."created_at" IS 'Fecha';

COMMENT ON COLUMN "ticket"."id" IS 'Identificador';

COMMENT ON COLUMN "ticket"."sale_id" IS 'Venta';

COMMENT ON COLUMN "ticket"."ticket_number" IS 'Numero';

COMMENT ON COLUMN "ticket"."issued_at" IS 'Fecha de Emision';

COMMENT ON COLUMN "return"."id" IS 'Identificador';

COMMENT ON COLUMN "return"."sale_id" IS 'Venta original';

COMMENT ON COLUMN "return"."user_id" IS 'Usuario Responsable';

COMMENT ON COLUMN "return"."type" IS 'Tipo';

COMMENT ON COLUMN "return"."reason" IS 'Motivo';

COMMENT ON COLUMN "return"."total" IS 'Total';

COMMENT ON COLUMN "return"."status" IS 'Estado';

COMMENT ON COLUMN "return"."created_at" IS 'Fecha';

COMMENT ON COLUMN "return_item"."id" IS 'Identificador';

COMMENT ON COLUMN "return_item"."return_id" IS 'Devolucion';

COMMENT ON COLUMN "return_item"."sale_item_id" IS 'Detalle Vendido';

COMMENT ON COLUMN "return_item"."quantity" IS 'Cantidad';

COMMENT ON COLUMN "return_item"."amount" IS 'Monto';

COMMENT ON COLUMN "reservation"."id" IS 'Identificador';

COMMENT ON COLUMN "reservation"."customer_id" IS 'Cliente';

COMMENT ON COLUMN "reservation"."user_id" IS 'Usuario';

COMMENT ON COLUMN "reservation"."status" IS 'Estado';

COMMENT ON COLUMN "reservation"."total" IS 'Total';

COMMENT ON COLUMN "reservation"."paid_amount" IS 'Pagado';

COMMENT ON COLUMN "reservation"."due_amount" IS 'Pendiente';

COMMENT ON COLUMN "reservation"."minimum_percentage_applied" IS 'Anticipo Aplicado';

COMMENT ON COLUMN "reservation"."cancellation_retention_percentage_applied" IS 'Retencion por Cancelacion';

COMMENT ON COLUMN "reservation"."expiration_retention_percentage_applied" IS 'Retencion por vencimiento';

COMMENT ON COLUMN "reservation"."reserved_at" IS 'Creacion';

COMMENT ON COLUMN "reservation"."expires_at" IS 'Vencimiento';

COMMENT ON COLUMN "reservation"."completed_at" IS 'Liquidacion';

COMMENT ON COLUMN "reservation"."cancelled_at" IS 'Cancelacion';

COMMENT ON COLUMN "reservation_item"."id" IS 'Identificador';

COMMENT ON COLUMN "reservation_item"."reservation_id" IS 'Apartado';

COMMENT ON COLUMN "reservation_item"."product_id" IS 'Producto';

COMMENT ON COLUMN "reservation_item"."quantity" IS 'Cantidad';

COMMENT ON COLUMN "reservation_item"."unit_price" IS 'Precio Historico';

COMMENT ON COLUMN "reservation_item"."subtotal" IS 'Subtotal';

COMMENT ON COLUMN "reservation_payment"."id" IS 'Identificador';

COMMENT ON COLUMN "reservation_payment"."reservation_id" IS 'Apartado';

COMMENT ON COLUMN "reservation_payment"."payment_method_id" IS 'Metodo de pago';

COMMENT ON COLUMN "reservation_payment"."amount" IS 'Monto';

COMMENT ON COLUMN "reservation_payment"."status" IS 'Estado';

COMMENT ON COLUMN "reservation_payment"."reference" IS 'Referencia';

COMMENT ON COLUMN "reservation_payment"."user_id" IS 'Usuario';

COMMENT ON COLUMN "reservation_payment"."created_at" IS 'Fecha';

COMMENT ON COLUMN "reservation_configuration"."id" IS 'Identificador';

COMMENT ON COLUMN "reservation_configuration"."minimum_percentage" IS 'Anticipo Minimo';

COMMENT ON COLUMN "reservation_configuration"."expiration_days" IS 'Dias de Vigencia';

COMMENT ON COLUMN "reservation_configuration"."cancellation_retention_percentage" IS 'Retencion por cancelacion';

COMMENT ON COLUMN "reservation_configuration"."expiration_retention_percentage" IS 'Retencion por vencimiento';

COMMENT ON COLUMN "reservation_configuration"."active" IS 'Estado';

COMMENT ON COLUMN "reservation_configuration"."created_at" IS 'Creacion';

COMMENT ON COLUMN "reservation_configuration"."updated_at" IS 'Actualizacion';

COMMENT ON COLUMN "supplier"."id" IS 'Identificador';

COMMENT ON COLUMN "supplier"."name" IS 'Nombre';

COMMENT ON COLUMN "supplier"."phone" IS 'Telefono';

COMMENT ON COLUMN "supplier"."email" IS 'Correo';

COMMENT ON COLUMN "supplier"."address" IS 'Direccion';

COMMENT ON COLUMN "supplier"."active" IS 'Estado';

COMMENT ON COLUMN "supplier"."created_at" IS 'Creacion';

COMMENT ON COLUMN "supplier"."updated_at" IS 'Actualizacion';

COMMENT ON COLUMN "product_supplier"."product_id" IS 'Producto';

COMMENT ON COLUMN "product_supplier"."supplier_id" IS 'Proveedor';

COMMENT ON COLUMN "product_supplier"."supplier_code" IS 'Codigo del proveedor';

COMMENT ON COLUMN "product_supplier"."last_purchase_price" IS 'Ultimo Costo Conocido';

COMMENT ON COLUMN "product_supplier"."active" IS 'Estado';

COMMENT ON COLUMN "purchase"."id" IS 'Identificador';

COMMENT ON COLUMN "purchase"."supplier_id" IS 'Proveedor';

COMMENT ON COLUMN "purchase"."user_id" IS 'Usuario Responsable';

COMMENT ON COLUMN "purchase"."status" IS 'Estado';

COMMENT ON COLUMN "purchase"."subtotal" IS 'Subtotal';

COMMENT ON COLUMN "purchase"."total" IS 'Total';

COMMENT ON COLUMN "purchase"."notes" IS 'Notas';

COMMENT ON COLUMN "purchase"."ordered_at" IS 'Fecha Pedido';

COMMENT ON COLUMN "purchase"."received_at" IS 'Fecha Recepcion';

COMMENT ON COLUMN "purchase"."created_at" IS 'Creacion';

COMMENT ON COLUMN "purchase_item"."id" IS 'Identificador';

COMMENT ON COLUMN "purchase_item"."purchase_id" IS 'Compra';

COMMENT ON COLUMN "purchase_item"."product_id" IS 'Producto';

COMMENT ON COLUMN "purchase_item"."quantity_ordered" IS 'Cantidad Solicitada';

COMMENT ON COLUMN "purchase_item"."quantity_received" IS 'Cantidad Recibida';

COMMENT ON COLUMN "purchase_item"."unit_cost" IS 'Costo Unitario';

COMMENT ON COLUMN "purchase_item"."subtotal" IS 'Subtotal';

COMMENT ON COLUMN "purchase_item"."notes" IS 'Notas';

COMMENT ON COLUMN "purchase_incident"."id" IS 'Identificador';

COMMENT ON COLUMN "purchase_incident"."purchase_id" IS 'Compra';

COMMENT ON COLUMN "purchase_incident"."purchase_item_id" IS 'Detalle';

COMMENT ON COLUMN "purchase_incident"."type" IS 'Tipo';

COMMENT ON COLUMN "purchase_incident"."quantity" IS 'Cantidad afectada';

COMMENT ON COLUMN "purchase_incident"."description" IS 'Descripcion';

COMMENT ON COLUMN "purchase_incident"."resolution" IS 'Resolucion';

COMMENT ON COLUMN "purchase_incident"."status" IS 'Estado';

COMMENT ON COLUMN "purchase_incident"."created_at" IS 'Creacion';

COMMENT ON COLUMN "purchase_incident"."resolved_at" IS 'Resolucion';

COMMENT ON COLUMN "cash_register"."id" IS 'Identificador';

COMMENT ON COLUMN "cash_register"."user_id" IS 'Usuario';

COMMENT ON COLUMN "cash_register"."status" IS 'Estado';

COMMENT ON COLUMN "cash_register"."opening_amount" IS 'Monto Inicial';

COMMENT ON COLUMN "cash_register"."opened_at" IS 'Apertura';

COMMENT ON COLUMN "cash_register"."closed_at" IS 'Cierre';

COMMENT ON COLUMN "cash_movement"."id" IS 'Identificador';

COMMENT ON COLUMN "cash_movement"."cash_register_id" IS 'Caja';

COMMENT ON COLUMN "cash_movement"."type" IS 'Tipo';

COMMENT ON COLUMN "cash_movement"."amount" IS 'Monto';

COMMENT ON COLUMN "cash_movement"."reference_type" IS 'Tipo de referencia';

COMMENT ON COLUMN "cash_movement"."reference_id" IS 'Referencia';

COMMENT ON COLUMN "cash_movement"."user_id" IS 'Usuario';

COMMENT ON COLUMN "cash_movement"."description" IS 'Descripcion';

COMMENT ON COLUMN "cash_movement"."created_at" IS 'Fecha';

COMMENT ON COLUMN "cash_closing"."id" IS 'Identificador';

COMMENT ON COLUMN "cash_closing"."cash_register_id" IS 'Caja';

COMMENT ON COLUMN "cash_closing"."user_id" IS 'Usuario';

COMMENT ON COLUMN "cash_closing"."expected_amount" IS 'Monto esperado';

COMMENT ON COLUMN "cash_closing"."actual_amount" IS 'Monto contado';

COMMENT ON COLUMN "cash_closing"."difference" IS 'Diferencia';

COMMENT ON COLUMN "cash_closing"."observations" IS 'Observaciones';

COMMENT ON COLUMN "cash_closing"."created_at" IS 'Fecha';

COMMENT ON COLUMN "invoice"."id" IS 'Identificador';

COMMENT ON COLUMN "invoice"."sale_id" IS 'Venta';

COMMENT ON COLUMN "invoice"."fiscal_data_id" IS 'Datos Fiscales';

COMMENT ON COLUMN "invoice"."provider" IS 'Proveedor';

COMMENT ON COLUMN "invoice"."external_id" IS 'Identificador Externo';

COMMENT ON COLUMN "invoice"."status" IS 'Estado';

COMMENT ON COLUMN "invoice"."issued_at" IS 'Fecha de emicion';

COMMENT ON COLUMN "invoice"."error_message" IS 'Error';

COMMENT ON COLUMN "invoice"."created_at" IS 'Creacion';

COMMENT ON COLUMN "invoice"."updated_at" IS 'Actualizacion';

COMMENT ON COLUMN "product_interest"."id" IS 'Identificador';

COMMENT ON COLUMN "product_interest"."customer_id" IS 'Cliente';

COMMENT ON COLUMN "product_interest"."product_id" IS 'Producto';

COMMENT ON COLUMN "product_interest"."requested_name" IS 'Nombre solicitado';

COMMENT ON COLUMN "product_interest"."notes" IS 'Notas';

COMMENT ON COLUMN "product_interest"."status" IS 'Estado';

COMMENT ON COLUMN "product_interest"."created_at" IS 'Fecha';

COMMENT ON COLUMN "business_configuration"."id" IS 'Identificador';

COMMENT ON COLUMN "business_configuration"."key" IS 'Clave';

COMMENT ON COLUMN "business_configuration"."value" IS 'Valor';

COMMENT ON COLUMN "business_configuration"."data_type" IS 'Tipo de dato';

COMMENT ON COLUMN "business_configuration"."description" IS 'Descripcion';

COMMENT ON COLUMN "business_configuration"."updated_by" IS 'Usuario';

COMMENT ON COLUMN "business_configuration"."updated_at" IS 'Actualizacion';

COMMENT ON COLUMN "audit_record"."id" IS 'Identificador';

COMMENT ON COLUMN "audit_record"."user_id" IS 'Usuario Responsable';

COMMENT ON COLUMN "audit_record"."action" IS 'Accion';

COMMENT ON COLUMN "audit_record"."entity_type" IS 'Tipo de Entidad';

COMMENT ON COLUMN "audit_record"."entity_id" IS 'Registro Afectado';

COMMENT ON COLUMN "audit_record"."old_value" IS 'Valor Anterior';

COMMENT ON COLUMN "audit_record"."new_value" IS 'Valor Nuevo';

COMMENT ON COLUMN "audit_record"."reason" IS 'Motivo';

COMMENT ON COLUMN "audit_record"."created_at" IS 'Fecha';


ALTER TABLE "reservation_item"
ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "return_item"
ADD FOREIGN KEY ("return_id") REFERENCES "return" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "role_permission"
ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "role_permission"
ADD FOREIGN KEY ("permission_id") REFERENCES "permission" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "fiscal_data"
ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "product"
ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "product"
ADD FOREIGN KEY ("brand_id") REFERENCES "brand" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "service_rate"
ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "inventory"
ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "inventory_movement"
ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "inventory_movement"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "inventory_incident"
ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "inventory_incident"
ADD FOREIGN KEY ("reported_by") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "inventory_incident"
ADD FOREIGN KEY ("resolved_by") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "sale"
ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "sale"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "sale_item"
ADD FOREIGN KEY ("sale_id") REFERENCES "sale" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "sale_item"
ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "sale_item"
ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "payment"
ADD FOREIGN KEY ("sale_id") REFERENCES "sale" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "payment"
ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_method" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ticket"
ADD FOREIGN KEY ("sale_id") REFERENCES "sale" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "sale_item"
ADD FOREIGN KEY ("discount_id") REFERENCES "discount" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "return"
ADD FOREIGN KEY ("sale_id") REFERENCES "sale" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "return"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "payment"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "return_item"
ADD FOREIGN KEY ("sale_item_id") REFERENCES "sale_item" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reservation"
ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reservation"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reservation_item"
ADD FOREIGN KEY ("reservation_id") REFERENCES "reservation" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reservation_payment"
ADD FOREIGN KEY ("reservation_id") REFERENCES "reservation" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reservation_payment"
ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_method" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reservation_payment"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "product_supplier"
ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "product_supplier"
ADD FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "purchase"
ADD FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "purchase"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "purchase_item"
ADD FOREIGN KEY ("purchase_id") REFERENCES "purchase" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "purchase_item"
ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "purchase_incident"
ADD FOREIGN KEY ("purchase_id") REFERENCES "purchase" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "purchase_incident"
ADD FOREIGN KEY ("purchase_item_id") REFERENCES "purchase_item" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "cash_register"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "cash_movement"
ADD FOREIGN KEY ("cash_register_id") REFERENCES "cash_register" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "cash_movement"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "cash_closing"
ADD FOREIGN KEY ("cash_register_id") REFERENCES "cash_register" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "cash_closing"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "invoice"
ADD FOREIGN KEY ("sale_id") REFERENCES "sale" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "invoice"
ADD FOREIGN KEY ("fiscal_data_id") REFERENCES "fiscal_data" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "product_interest"
ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "product_interest"
ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "business_configuration"
ADD FOREIGN KEY ("updated_by") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "audit_record"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user_role"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user_role"
ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;