-- SEED: CLIENTES
-- Inserta clientes representativos para desarrollo y pruebas.
--
-- Los valores son ficticios y estan destinados únicamente al
-- desarrollo local y a pruebas de base de datos.

INSERT INTO
    "customer" (
        "first_name",
        "paternal_last_name",
        "maternal_last_name",
        "phone",
        "email"
    )
VALUES (
        'Alejandro',
        'Ramirez',
        'Torres',
        '5512345678',
        'alejandro.ramirez@example.com'
    ),
    (
        'Beatriz',
        'Morales',
        'Hernandez',
        '5523456789',
        'beatriz.morales@example.com'
    ),
    (
        'Carlos',
        'Gonzalez',
        'Martinez',
        '5534567890',
        'carlos.gonzalez@example.com'
    ),
    (
        'Diana',
        'Lopez',
        'Garcia',
        '5545678901',
        'diana.lopez@example.com'
    ),
    (
        'Eduardo',
        'Martinez',
        'Ruiz',
        '5556789012',
        'eduardo.martinez@example.com'
    ),
    (
        'Fernanda',
        'Castillo',
        'Mendoza',
        '5567890123',
        'fernanda.castillo@example.com'
    ),
    (
        'Gabriel',
        'Torres',
        'Ramirez',
        '5578901234',
        'gabriel.torres@example.com'
    ),
    (
        'Hilda',
        'Navarro',
        'Flores',
        '5589012345',
        'hilda.navarro@example.com'
    ),
    (
        'Ivan',
        'Sanchez',
        'Vargas',
        '5590123456',
        'ivan.sanchez@example.com'
    ),
    (
        'Julieta',
        'Rojas',
        'Morales',
        '5510234567',
        'julieta.rojas@example.com'
    ),
    (
        'Kevin',
        'Hernandez',
        'Cruz',
        '5521345678',
        'kevin.hernandez@example.com'
    ),
    (
        'Laura',
        'Vargas',
        'Jimenez',
        '5532456789',
        'laura.vargas@example.com'
    ),
    (
        'Manuel',
        'Flores',
        'Ortega',
        '5543567890',
        'manuel.flores@example.com'
    ),
    (
        'Natalia',
        'Mendoza',
        'Reyes',
        '5554678901',
        'natalia.mendoza@example.com'
    ),
    (
        'Oscar',
        'Ruiz',
        'Santos',
        '5565789012',
        'oscar.ruiz@example.com'
    ),
    (
        'Patricia',
        'Jimenez',
        'Salazar',
        '5576890123',
        'patricia.jimenez@example.com'
    ),
    (
        'Ricardo',
        'Ortega',
        'Valdez',
        '5587901234',
        'ricardo.ortega@example.com'
    ),
    (
        'Sofia',
        'Reyes',
        'Guerrero',
        '5598012345',
        'sofia.reyes@example.com'
    ),
    (
        'Tomas',
        'Santos',
        'Mendez',
        '5519123456',
        'tomas.santos@example.com'
    ),
    (
        'Valeria',
        'Salazar',
        'Fuentes',
        '5520234567',
        'valeria.salazar@example.com'
    ),
    (
        'Andres',
        'Valdez',
        'Dominguez',
        '5531345678',
        'andres.valdez@example.com'
    ),
    (
        'Carolina',
        'Guerrero',
        'Nunez',
        '5542456789',
        'carolina.guerrero@example.com'
    ),
    (
        'Diego',
        'Mendez',
        'Ibarra',
        '5553567890',
        'diego.mendez@example.com'
    ),
    (
        'Elena',
        'Fuentes',
        'Valencia',
        '5564678901',
        'elena.fuentes@example.com'
    ),
    (
        'Francisco',
        'Dominguez',
        'Pineda',
        '5575789012',
        'francisco.dominguez@example.com'
    ),
    (
        'Gabriela',
        'Nunez',
        'Campos',
        '5586890123',
        'gabriela.nunez@example.com'
    ),
    (
        'Hector',
        'Ibarra',
        'Estrada',
        '5597901234',
        'hector.ibarra@example.com'
    ),
    (
        'Isabel',
        'Valencia',
        'Leon',
        '5518012345',
        'isabel.valencia@example.com'
    ),
    (
        'Jorge',
        'Pineda',
        'Valdez',
        '5529123456',
        'jorge.pineda@example.com'
    ),
    (
        'Karen',
        'Campos',
        'Mora',
        '5530234567',
        'karen.campos@example.com'
    ),
    (
        'Luis',
        'Estrada',
        'Cervantes',
        '5541345678',
        'luis.estrada@example.com'
    ),
    (
        'Mariana',
        'Leon',
        'Ramos',
        '5552456789',
        'mariana.leon@example.com'
    ),
    (
        'Nicolas',
        'Cervantes',
        'Molina',
        '5563567890',
        'nicolas.cervantes@example.com'
    ),
    (
        'Olivia',
        'Ramos',
        'Mendoza',
        '5574678901',
        'olivia.ramos@example.com'
    ),
    (
        'Pablo',
        'Molina',
        'Serrano',
        '5585789012',
        'pablo.molina@example.com'
    ),
    (
        'Raquel',
        'Serrano',
        'Duarte',
        '5596890123',
        'raquel.serrano@example.com'
    ),
    (
        'Samuel',
        'Duarte',
        'Miranda',
        '5517901234',
        'samuel.duarte@example.com'
    ),
    (
        'Teresa',
        'Miranda',
        'Cortes',
        '5528012345',
        'teresa.miranda@example.com'
    ),
    (
        'Ulises',
        'Cortes',
        'Maldonado',
        '5539123456',
        'ulises.cortes@example.com'
    ),
    (
        'Veronica',
        'Maldonado',
        'Bravo',
        '5540234567',
        'veronica.maldonado@example.com'
    ),
    (
        'Adrian',
        'Bravo',
        'Rosales',
        '5551345678',
        'adrian.bravo@example.com'
    ),
    (
        'Brenda',
        'Rosales',
        'Espinoza',
        '5562456789',
        'brenda.rosales@example.com'
    ),
    (
        'Cesar',
        'Espinoza',
        'Mejia',
        '5573567890',
        'cesar.espinoza@example.com'
    ),
    (
        'Daniela',
        'Mejia',
        'Zamora',
        '5584678901',
        'daniela.mejia@example.com'
    ),
    (
        'Enrique',
        'Zamora',
        'Padilla',
        '5595789012',
        'enrique.zamora@example.com'
    ),
    (
        'Fabiola',
        'Padilla',
        'Velasco',
        '5516890123',
        'fabiola.padilla@example.com'
    ),
    (
        'Gustavo',
        'Velasco',
        'Arias',
        '5527901234',
        'gustavo.velasco@example.com'
    ),
    (
        'Helena',
        'Arias',
        'Cabrera',
        '5538012345',
        'helena.arias@example.com'
    ),
    (
        'Mauricio',
        'Cabrera',
        'Duran',
        '5549123456',
        'mauricio.cabrera@example.com'
    ),
    (
        'Regina',
        'Duran',
        'Mora',
        '5550234567',
        'regina.duran@example.com'
    ),
    (
        'Victor',
        'Mora',
        'Solis',
        '5561345678',
        'victor.mora@example.com'
    ),
    (
        'Yolanda',
        'Solis',
        'Mendez',
        '5572456789',
        'yolanda.solis@example.com'
    ),
    (
        'Zoe',
        'Mendez',
        'Rios',
        '5583567890',
        'zoe.mendez@example.com'
    )
ON CONFLICT DO NOTHING;