-- SEED: PRODUCTOS
--
-- Inserta productos representativos de una papeleria.
--
-- Los nombres corresponden a productos y marcas comercializados
-- en Mexico. Los precios, costos, codigos de barras y fechas son
-- datos destinados al desarrollo local y a pruebas de base de datos.
--
-- Las categorias y marcas se obtienen por nombre para evitar
-- depender de los IDs generados por la base de datos.

WITH seed_products (
    sku,
    barcode,
    name,
    description,
    category_name,
    brand_name,
    sale_price,
    cost_price,
    stock_alert_level,
    active,
    created_at,
    updated_at
) AS (
    VALUES
    -- ESCRITURA
    (
        'PAP-DIX-001',
        '7501234500001',
        'Lapiz Dixon No. 2',
        'Lapiz de grafito para escritura y uso escolar.',
        'Escritura',
        'Dixon',
        8.50,
        4.20,
        20,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '3 months'
    ),
    (
        'PAP-DIX-002',
        '7501234500002',
        'Lapiz Dixon Triangular',
        'Lapiz triangular de grafito para escritura.',
        'Escritura',
        'Dixon',
        12.50,
        6.30,
        15,
        TRUE,
        NOW() - INTERVAL '18 months',
        NOW() - INTERVAL '20 days'
    ),
    (
        'PAP-FAB-001',
        '7501234500003',
        'Lapiz Faber-Castell HB',
        'Lapiz de grafito grado HB.',
        'Escritura',
        'Faber-Castell',
        10.00,
        5.00,
        20,
        TRUE,
        NOW() - INTERVAL '14 months',
        NOW() - INTERVAL '5 days'
    ),
    (
        'PAP-FAB-002',
        '7501234500004',
        'Lapiz Faber-Castell 2B',
        'Lapiz de grafito 2B para dibujo y escritura.',
        'Escritura',
        'Faber-Castell',
        11.50,
        5.80,
        15,
        TRUE,
        NOW() - INTERVAL '10 months',
        NOW() - INTERVAL '40 days'
    ),
    (
        'PAP-BIC-001',
        '7501234500005',
        'Boligrafo BIC Cristal Negro',
        'Boligrafo de tinta negra para escritura cotidiana.',
        'Escritura',
        'BIC',
        7.00,
        3.20,
        25,
        TRUE,
        NOW() - INTERVAL '20 months',
        NOW() - INTERVAL '2 days'
    ),
    (
        'PAP-BIC-002',
        '7501234500006',
        'Boligrafo BIC Cristal Azul',
        'Boligrafo de tinta azul para escritura cotidiana.',
        'Escritura',
        'BIC',
        7.00,
        3.20,
        25,
        TRUE,
        NOW() - INTERVAL '15 months',
        NOW() - INTERVAL '12 days'
    ),
    (
        'PAP-PIL-001',
        '7501234500007',
        'Boligrafo Pilot Super Grip',
        'Boligrafo de tinta azul con grip ergonomico.',
        'Escritura',
        'Pilot',
        32.00,
        18.00,
        10,
        TRUE,
        NOW() - INTERVAL '9 months',
        NOW() - INTERVAL '8 days'
    ),
    (
        'PAP-PEN-001',
        '7501234500008',
        'Boligrafo Pentel EnerGel',
        'Boligrafo de gel para escritura fluida.',
        'Escritura',
        'Pentel',
        48.00,
        28.00,
        10,
        TRUE,
        NOW() - INTERVAL '7 months',
        NOW() - INTERVAL '15 days'
    ),
    (
        'PAP-PMA-001',
        '7501234500009',
        'Boligrafo Paper Mate InkJoy',
        'Boligrafo de tinta de secado rapido.',
        'Escritura',
        'Paper Mate',
        18.00,
        9.00,
        15,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '3 days'
    ),
    (
        'PAP-DIX-003',
        '7501234500010',
        'Lapiz Rojo Dixon',
        'Lapiz de color rojo para escritura y marcado.',
        'Escritura',
        'Dixon',
        9.00,
        4.50,
        15,
        FALSE,
        NOW() - INTERVAL '3 years',
        NOW() - INTERVAL '18 months'
    ),
    -- COLORES
    (
        'PAP-DIX-011',
        '7501234500011',
        'Colores Mapita 12 piezas',
        'Caja de lapices de colores para uso escolar.',
        'Colores',
        'Dixon',
        38.00,
        20.00,
        15,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '10 days'
    ),
    (
        'PAP-DIX-012',
        '7501234500012',
        'Colores Mapita 24 piezas',
        'Caja de lapices de colores de 24 piezas.',
        'Colores',
        'Dixon',
        72.00,
        40.00,
        10,
        TRUE,
        NOW() - INTERVAL '16 months',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-CRA-001',
        '7501234500013',
        'Crayones Crayola 12 piezas',
        'Caja de crayones de colores para actividades escolares.',
        'Colores',
        'Crayola',
        48.00,
        25.00,
        15,
        TRUE,
        NOW() - INTERVAL '13 months',
        NOW() - INTERVAL '6 days'
    ),
    (
        'PAP-CRA-002',
        '7501234500014',
        'Crayones Crayola 24 piezas',
        'Caja de crayones de colores de 24 piezas.',
        'Colores',
        'Crayola',
        82.00,
        45.00,
        10,
        TRUE,
        NOW() - INTERVAL '11 months',
        NOW() - INTERVAL '2 months'
    ),
    (
        'PAP-FAB-011',
        '7501234500015',
        'Colores Faber-Castell 12 piezas',
        'Lapices de colores para dibujo y actividades escolares.',
        'Colores',
        'Faber-Castell',
        65.00,
        34.00,
        10,
        TRUE,
        NOW() - INTERVAL '8 months',
        NOW() - INTERVAL '7 days'
    ),
    (
        'PAP-FAB-012',
        '7501234500016',
        'Colores Faber-Castell 24 piezas',
        'Lapices de colores de 24 piezas.',
        'Colores',
        'Faber-Castell',
        120.00,
        65.00,
        8,
        TRUE,
        NOW() - INTERVAL '5 months',
        NOW() - INTERVAL '20 days'
    ),
    (
        'PAP-NOR-001',
        '7501234500017',
        'Colores Norma 12 piezas',
        'Lapices de colores para uso escolar.',
        'Colores',
        'Norma',
        42.00,
        22.00,
        15,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '4 months'
    ),
    (
        'PAP-NOR-002',
        '7501234500018',
        'Colores Norma 24 piezas',
        'Lapices de colores de 24 piezas.',
        'Colores',
        'Norma',
        78.00,
        42.00,
        10,
        TRUE,
        NOW() - INTERVAL '9 months',
        NOW() - INTERVAL '12 days'
    ),
    -- MARCADORES
    (
        'PAP-SHA-001',
        '7501234500019',
        'Marcadores Sharpie Negro',
        'Marcador permanente de tinta negra.',
        'Marcadores',
        'Sharpie',
        32.00,
        18.00,
        12,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '15 days'
    ),
    (
        'PAP-SHA-002',
        '7501234500020',
        'Marcadores Sharpie Colores 12 piezas',
        'Set de marcadores permanentes de diferentes colores.',
        'Marcadores',
        'Sharpie',
        210.00,
        125.00,
        5,
        TRUE,
        NOW() - INTERVAL '14 months',
        NOW() - INTERVAL '2 days'
    ),
    (
        'PAP-STA-001',
        '7501234500021',
        'Marcadores Stabilo Boss 4 piezas',
        'Set de marcatextos de colores.',
        'Marcadores',
        'Stabilo',
        115.00,
        65.00,
        8,
        TRUE,
        NOW() - INTERVAL '10 months',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-STA-002',
        '7501234500022',
        'Marcador Stabilo Negro',
        'Marcador de punta fina para escritura.',
        'Marcadores',
        'Stabilo',
        25.00,
        13.00,
        15,
        TRUE,
        NOW() - INTERVAL '7 months',
        NOW() - INTERVAL '4 days'
    ),
    (
        'PAP-NOR-011',
        '7501234500023',
        'Plumones Norma 12 piezas',
        'Set de plumones escolares de colores.',
        'Marcadores',
        'Norma',
        58.00,
        30.00,
        10,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '18 days'
    ),
    -- CUADERNOS
    (
        'PAP-SCR-001',
        '7501234500024',
        'Cuaderno Scribe Profesional 100 hojas',
        'Cuaderno profesional de 100 hojas para uso escolar.',
        'Cuadernos',
        'Scribe',
        52.00,
        30.00,
        20,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '7 days'
    ),
    (
        'PAP-SCR-002',
        '7501234500025',
        'Cuaderno Scribe Profesional 200 hojas',
        'Cuaderno profesional de 200 hojas.',
        'Cuadernos',
        'Scribe',
        92.00,
        54.00,
        15,
        TRUE,
        NOW() - INTERVAL '15 months',
        NOW() - INTERVAL '2 months'
    ),
    (
        'PAP-NOR-021',
        '7501234500026',
        'Cuaderno Norma Profesional 100 hojas',
        'Cuaderno profesional para notas y actividades escolares.',
        'Cuadernos',
        'Norma',
        65.00,
        37.00,
        15,
        TRUE,
        NOW() - INTERVAL '12 months',
        NOW() - INTERVAL '11 days'
    ),
    (
        'PAP-NOR-022',
        '7501234500027',
        'Cuaderno Norma Cosido',
        'Cuaderno cosido para uso escolar.',
        'Cuadernos',
        'Norma',
        58.00,
        32.00,
        15,
        TRUE,
        NOW() - INTERVAL '8 months',
        NOW() - INTERVAL '5 days'
    ),
    (
        'PAP-SCR-003',
        '7501234500028',
        'Libreta Scribe 80 hojas',
        'Libreta para notas y uso cotidiano.',
        'Cuadernos',
        'Scribe',
        38.00,
        21.00,
        15,
        TRUE,
        NOW() - INTERVAL '5 months',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-SCR-004',
        '7501234500029',
        'Cuaderno Scribe Cuadro Grande',
        'Cuaderno escolar con hojas de cuadro grande.',
        'Cuadernos',
        'Scribe',
        42.00,
        24.00,
        20,
        FALSE,
        NOW() - INTERVAL '3 years',
        NOW() - INTERVAL '2 years'
    ),
    -- PAPEL Y CARTULINA
    (
        'PAP-COP-001',
        '7501234500030',
        'Papel Bond Carta 500 hojas',
        'Paquete de papel bond tamano carta.',
        'Papel',
        'Copamex',
        125.00,
        82.00,
        10,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '3 days'
    ),
    (
        'PAP-COP-002',
        '7501234500031',
        'Papel Bond Oficio 500 hojas',
        'Paquete de papel bond tamano oficio.',
        'Papel',
        'Copamex',
        165.00,
        105.00,
        8,
        TRUE,
        NOW() - INTERVAL '18 months',
        NOW() - INTERVAL '2 weeks'
    ),
    (
        'PAP-COP-003',
        '7501234500032',
        'Papel Bond Carta 100 hojas',
        'Paquete pequeno de papel bond tamano carta.',
        'Papel',
        'Copamex',
        35.00,
        20.00,
        15,
        TRUE,
        NOW() - INTERVAL '9 months',
        NOW() - INTERVAL '10 days'
    ),
    (
        'PAP-MAE-001',
        '7501234500033',
        'Cartulina Blanca',
        'Cartulina blanca para trabajos escolares y manualidades.',
        'Cartulina',
        'MAE',
        8.00,
        4.00,
        30,
        TRUE,
        NOW() - INTERVAL '11 months',
        NOW() - INTERVAL '6 days'
    ),
    (
        'PAP-MAE-002',
        '7501234500034',
        'Cartulina Colores',
        'Cartulina de colores surtidos.',
        'Cartulina',
        'MAE',
        10.00,
        5.00,
        30,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '20 days'
    ),
    (
        'PAP-NOR-031',
        '7501234500035',
        'Hojas Decoradas Norma',
        'Hojas decorativas para trabajos escolares y manualidades.',
        'Papel',
        'Norma',
        35.00,
        18.00,
        10,
        FALSE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '1 year'
    ),
    -- ADHESIVOS
    (
        'PAP-RES-001',
        '7501234500036',
        'Resistol Blanco 850',
        'Adhesivo blanco para trabajos escolares y manualidades.',
        'Adhesivos',
        'Resistol',
        32.00,
        17.00,
        15,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '4 days'
    ),
    (
        'PAP-RES-002',
        '7501234500037',
        'Resistol 5000',
        'Adhesivo de contacto para diferentes materiales.',
        'Adhesivos',
        'Resistol',
        68.00,
        38.00,
        10,
        TRUE,
        NOW() - INTERVAL '16 months',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-PRI-001',
        '7501234500038',
        'Pegamento Pritt 10 g',
        'Pegamento en barra para uso escolar.',
        'Adhesivos',
        'Pritt',
        28.00,
        14.00,
        20,
        TRUE,
        NOW() - INTERVAL '13 months',
        NOW() - INTERVAL '8 days'
    ),
    (
        'PAP-PRI-002',
        '7501234500039',
        'Pegamento Pritt 20 g',
        'Pegamento en barra de 20 gramos.',
        'Adhesivos',
        'Pritt',
        42.00,
        22.00,
        15,
        TRUE,
        NOW() - INTERVAL '8 months',
        NOW() - INTERVAL '12 days'
    ),
    (
        'PAP-UHU-001',
        '7501234500040',
        'Pegamento UHU Liquido',
        'Adhesivo liquido para trabajos escolares y manualidades.',
        'Adhesivos',
        'UHU',
        45.00,
        25.00,
        10,
        TRUE,
        NOW() - INTERVAL '7 months',
        NOW() - INTERVAL '3 days'
    ),
    -- PLASTILINA Y MANUALIDADES
    (
        'PAP-CRA-011',
        '7501234500041',
        'Plastilina Crayola 8 colores',
        'Plastilina para actividades escolares y creativas.',
        'Plastilina',
        'Crayola',
        45.00,
        23.00,
        10,
        TRUE,
        NOW() - INTERVAL '20 months',
        NOW() - INTERVAL '15 days'
    ),
    (
        'PAP-JOV-001',
        '7501234500042',
        'Plastilina Jovi 10 colores',
        'Plastilina para modelado y actividades escolares.',
        'Plastilina',
        'Jovi',
        68.00,
        35.00,
        10,
        TRUE,
        NOW() - INTERVAL '12 months',
        NOW() - INTERVAL '20 days'
    ),
    (
        'PAP-JOV-002',
        '7501234500043',
        'Plastilina Jovi 15 colores',
        'Set de plastilina de varios colores.',
        'Plastilina',
        'Jovi',
        92.00,
        50.00,
        8,
        TRUE,
        NOW() - INTERVAL '9 months',
        NOW() - INTERVAL '5 days'
    ),
    (
        'PAP-COL-001',
        '7501234500044',
        'Plastilina Colorim',
        'Plastilina para modelado y actividades escolares.',
        'Plastilina',
        'Colorim',
        28.00,
        14.00,
        15,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '2 months'
    ),
    (
        'PAP-CRA-012',
        '7501234500045',
        'Kit de Manualidades Crayola',
        'Materiales variados para actividades creativas.',
        'Manualidades',
        'Crayola',
        145.00,
        82.00,
        5,
        TRUE,
        NOW() - INTERVAL '5 months',
        NOW() - INTERVAL '10 days'
    ),
    -- PINTURA
    (
        'PAP-VIN-001',
        '7501234500046',
        'Pintura Vinci 10 colores',
        'Pintura escolar de colores variados.',
        'Pintura',
        'Vinci',
        85.00,
        45.00,
        8,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '12 days'
    ),
    (
        'PAP-VIN-002',
        '7501234500047',
        'Pintura Vinci 6 colores',
        'Set de pintura escolar de seis colores.',
        'Pintura',
        'Vinci',
        58.00,
        30.00,
        10,
        TRUE,
        NOW() - INTERVAL '14 months',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-VIN-003',
        '7501234500048',
        'Pintura Vinci Negra',
        'Pintura escolar color negro.',
        'Pintura',
        'Vinci',
        18.00,
        9.00,
        15,
        TRUE,
        NOW() - INTERVAL '8 months',
        NOW() - INTERVAL '7 days'
    ),
    (
        'PAP-VIN-004',
        '7501234500049',
        'Pintura Vinci Blanca',
        'Pintura escolar color blanco.',
        'Pintura',
        'Vinci',
        18.00,
        9.00,
        15,
        FALSE,
        NOW() - INTERVAL '3 years',
        NOW() - INTERVAL '2 years'
    ),
    -- DIBUJO
    (
        'PAP-FAB-021',
        '7501234500050',
        'Set de Dibujo Faber-Castell',
        'Set de materiales para dibujo.',
        'Dibujo',
        'Faber-Castell',
        165.00,
        92.00,
        5,
        TRUE,
        NOW() - INTERVAL '10 months',
        NOW() - INTERVAL '14 days'
    ),
    (
        'PAP-STA-011',
        '7501234500051',
        'Lapiz Staedtler Mars Lumograph',
        'Lapiz profesional para dibujo.',
        'Dibujo',
        'Staedtler',
        35.00,
        19.00,
        10,
        TRUE,
        NOW() - INTERVAL '7 months',
        NOW() - INTERVAL '5 days'
    ),
    (
        'PAP-STA-012',
        '7501234500052',
        'Set Staedtler para Dibujo',
        'Set de lapices y accesorios para dibujo.',
        'Dibujo',
        'Staedtler',
        220.00,
        125.00,
        5,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-PRI-011',
        '7501234500053',
        'Colores Prismacolor Premier',
        'Lapices de colores para dibujo artistico.',
        'Dibujo',
        'Prismacolor',
        390.00,
        230.00,
        5,
        TRUE,
        NOW() - INTERVAL '4 months',
        NOW() - INTERVAL '9 days'
    ),
    -- GEOMETRIA
    (
        'PAP-MAP-001',
        '7501234500054',
        'Regla Maped 30 cm',
        'Regla plastica transparente de 30 centimetros.',
        'Geometria',
        'Maped',
        18.00,
        9.00,
        20,
        TRUE,
        NOW() - INTERVAL '18 months',
        NOW() - INTERVAL '2 days'
    ),
    (
        'PAP-MAP-002',
        '7501234500055',
        'Escuadras Maped',
        'Juego de escuadras para geometria.',
        'Geometria',
        'Maped',
        38.00,
        20.00,
        10,
        TRUE,
        NOW() - INTERVAL '13 months',
        NOW() - INTERVAL '15 days'
    ),
    (
        'PAP-MAP-003',
        '7501234500056',
        'Compas Maped',
        'Compas escolar para geometria.',
        'Geometria',
        'Maped',
        75.00,
        40.00,
        8,
        TRUE,
        NOW() - INTERVAL '8 months',
        NOW() - INTERVAL '20 days'
    ),
    (
        'PAP-PEL-001',
        '7501234500057',
        'Juego Geometrico Pelikan',
        'Juego de instrumentos geometricos escolares.',
        'Geometria',
        'Pelikan',
        48.00,
        25.00,
        10,
        TRUE,
        NOW() - INTERVAL '7 months',
        NOW() - INTERVAL '3 days'
    ),
    -- CORTE
    (
        'PAP-MAP-011',
        '7501234500058',
        'Tijeras Maped Escolares',
        'Tijeras escolares de punta redonda.',
        'Corte',
        'Maped',
        35.00,
        18.00,
        15,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-MAP-012',
        '7501234500059',
        'Tijeras Maped 13 cm',
        'Tijeras escolares de 13 centimetros.',
        'Corte',
        'Maped',
        48.00,
        25.00,
        10,
        TRUE,
        NOW() - INTERVAL '10 months',
        NOW() - INTERVAL '8 days'
    ),
    (
        'PAP-BAR-001',
        '7501234500060',
        'Tijeras Barrilito Escolares',
        'Tijeras escolares para trabajos manuales.',
        'Corte',
        'Barrilito',
        28.00,
        14.00,
        15,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '6 days'
    ),
    -- CORRECTORES Y BORRADORE
    (
        'PAP-PEL-011',
        '7501234500061',
        'Goma Pelikan Blanca',
        'Goma blanca para borrar grafito.',
        'Borradores',
        'Pelikan',
        9.00,
        4.00,
        25,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '4 days'
    ),
    (
        'PAP-FAB-031',
        '7501234500062',
        'Goma Faber-Castell',
        'Goma blanca para borrar lapiz.',
        'Borradores',
        'Faber-Castell',
        12.00,
        6.00,
        20,
        TRUE,
        NOW() - INTERVAL '15 months',
        NOW() - INTERVAL '12 days'
    ),
    (
        'PAP-PEL-012',
        '7501234500063',
        'Sacapuntas Pelikan',
        'Sacapuntas escolar de plastico.',
        'Sacapuntas',
        'Pelikan',
        15.00,
        7.00,
        20,
        TRUE,
        NOW() - INTERVAL '11 months',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-FAB-032',
        '7501234500064',
        'Sacapuntas Faber-Castell',
        'Sacapuntas escolar con deposito.',
        'Sacapuntas',
        'Faber-Castell',
        28.00,
        14.00,
        15,
        TRUE,
        NOW() - INTERVAL '8 months',
        NOW() - INTERVAL '10 days'
    ),
    (
        'PAP-STA-021',
        '7501234500065',
        'Corrector Stabilo',
        'Corrector para escritura y trabajos escolares.',
        'Correctores',
        'Stabilo',
        32.00,
        17.00,
        10,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '5 days'
    ),
    -- ORGANIZACION Y ARCHIVADO
    (
        'PAP-BAR-011',
        '7501234500066',
        'Folder Barrilito Carta',
        'Folder para organizacion y archivo de documentos.',
        'Archivado',
        'Barrilito',
        12.00,
        6.00,
        25,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '7 days'
    ),
    (
        'PAP-BAR-012',
        '7501234500067',
        'Carpeta Barrilito 3 anillos',
        'Carpeta de tres anillos para documentos.',
        'Archivado',
        'Barrilito',
        85.00,
        45.00,
        10,
        TRUE,
        NOW() - INTERVAL '17 months',
        NOW() - INTERVAL '20 days'
    ),
    (
        'PAP-MAE-011',
        '7501234500068',
        'Folder Mae Oficio',
        'Folder tamano oficio para documentos.',
        'Archivado',
        'MAE',
        15.00,
        7.00,
        20,
        TRUE,
        NOW() - INTERVAL '12 months',
        NOW() - INTERVAL '3 days'
    ),
    (
        'PAP-BAR-013',
        '7501234500069',
        'Caja Organizadora Barrilito',
        'Caja plastica para organizar materiales.',
        'Organizacion',
        'Barrilito',
        95.00,
        52.00,
        8,
        TRUE,
        NOW() - INTERVAL '9 months',
        NOW() - INTERVAL '1 month'
    ),
    -- OFICINA
    (
        'PAP-BAR-021',
        '7501234500070',
        'Grapadora Barrilito',
        'Grapadora de escritorio para oficina.',
        'Oficina',
        'Barrilito',
        65.00,
        35.00,
        10,
        TRUE,
        NOW() - INTERVAL '2 years',
        NOW() - INTERVAL '15 days'
    ),
    (
        'PAP-BAR-022',
        '7501234500071',
        'Perforadora Barrilito',
        'Perforadora de dos orificios para documentos.',
        'Oficina',
        'Barrilito',
        78.00,
        42.00,
        8,
        TRUE,
        NOW() - INTERVAL '14 months',
        NOW() - INTERVAL '10 days'
    ),
    (
        'PAP-STA-031',
        '7501234500072',
        'Marcador Permanente Staedtler',
        'Marcador permanente de tinta negra.',
        'Oficina',
        'Staedtler',
        28.00,
        15.00,
        15,
        TRUE,
        NOW() - INTERVAL '10 months',
        NOW() - INTERVAL '4 days'
    ),
    (
        'PAP-SCO-001',
        '7501234500073',
        'Cinta Adhesiva Scotch',
        'Cinta adhesiva transparente para oficina.',
        'Oficina',
        'Scotch',
        38.00,
        20.00,
        15,
        TRUE,
        NOW() - INTERVAL '7 months',
        NOW() - INTERVAL '2 months'
    ),
    (
        'PAP-SCO-002',
        '7501234500074',
        'Cinta Masking Scotch',
        'Cinta adhesiva de papel para diferentes usos.',
        'Oficina',
        'Scotch',
        52.00,
        28.00,
        10,
        FALSE,
        NOW() - INTERVAL '3 years',
        NOW() - INTERVAL '2 years'
    ),
    -- MATERIAL DIDACTICO Y ESCOLAR
    (
        'PAP-PEL-021',
        '7501234500075',
        'Acuarelas Pelikan',
        'Set de acuarelas para actividades escolares.',
        'Material Didactico',
        'Pelikan',
        55.00,
        28.00,
        10,
        TRUE,
        NOW() - INTERVAL '16 months',
        NOW() - INTERVAL '5 days'
    ),
    (
        'PAP-VIN-011',
        '7501234500076',
        'Pintura Dactilar Vinci',
        'Pintura dactilar para actividades escolares.',
        'Material Didactico',
        'Vinci',
        78.00,
        40.00,
        8,
        TRUE,
        NOW() - INTERVAL '11 months',
        NOW() - INTERVAL '15 days'
    ),
    (
        'PAP-CRA-021',
        '7501234500077',
        'Kit Escolar Crayola',
        'Kit de materiales para actividades escolares.',
        'Escolar',
        'Crayola',
        135.00,
        75.00,
        5,
        TRUE,
        NOW() - INTERVAL '9 months',
        NOW() - INTERVAL '2 weeks'
    ),
    (
        'PAP-NOR-041',
        '7501234500078',
        'Kit Escolar Norma',
        'Kit de utiles escolares variados.',
        'Escolar',
        'Norma',
        145.00,
        80.00,
        5,
        TRUE,
        NOW() - INTERVAL '7 months',
        NOW() - INTERVAL '3 days'
    ),
    (
        'PAP-DIX-021',
        '7501234500079',
        'Kit de Lapices Dixon',
        'Kit de lapices para uso escolar.',
        'Escolar',
        'Dixon',
        48.00,
        25.00,
        10,
        TRUE,
        NOW() - INTERVAL '5 months',
        NOW() - INTERVAL '1 month'
    ),
    -- ETIQUETADO Y PRESENTACION
    (
        'PAP-SCR-011',
        '7501234500080',
        'Etiquetas Scribe Escolares',
        'Etiquetas para identificar utiles escolares.',
        'Etiquetado',
        'Scribe',
        25.00,
        12.00,
        15,
        TRUE,
        NOW() - INTERVAL '13 months',
        NOW() - INTERVAL '8 days'
    ),
    (
        'PAP-MAE-021',
        '7501234500081',
        'Etiquetas Mae Adhesivas',
        'Etiquetas adhesivas para organizacion.',
        'Etiquetado',
        'MAE',
        32.00,
        16.00,
        10,
        TRUE,
        NOW() - INTERVAL '8 months',
        NOW() - INTERVAL '20 days'
    ),
    (
        'PAP-BAR-031',
        '7501234500082',
        'Micas Barrilito Carta',
        'Micas transparentes para proteccion y presentacion de documentos.',
        'Presentacion',
        'Barrilito',
        48.00,
        25.00,
        10,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '5 days'
    ),
    (
        'PAP-BAR-032',
        '7501234500083',
        'Micas Barrilito Oficio',
        'Micas transparentes tamano oficio.',
        'Presentacion',
        'Barrilito',
        58.00,
        30.00,
        10,
        TRUE,
        NOW() - INTERVAL '4 months',
        NOW() - INTERVAL '12 days'
    ),
    -- PRODUCTOS SIN MARCA
    (
        'PAP-GEN-001',
        NULL,
        'Papel China Rojo',
        'Hoja de papel china para manualidades.',
        'Manualidades',
        NULL,
        6.00,
        2.50,
        30,
        TRUE,
        NOW() - INTERVAL '18 months',
        NOW() - INTERVAL '5 days'
    ),
    (
        'PAP-GEN-002',
        NULL,
        'Papel China Azul',
        'Hoja de papel china para manualidades.',
        'Manualidades',
        NULL,
        6.00,
        2.50,
        30,
        TRUE,
        NOW() - INTERVAL '14 months',
        NOW() - INTERVAL '2 months'
    ),
    (
        'PAP-GEN-003',
        NULL,
        'Foamy Rojo',
        'Lamina de foamy para manualidades.',
        'Manualidades',
        NULL,
        12.00,
        6.00,
        25,
        TRUE,
        NOW() - INTERVAL '10 months',
        NOW() - INTERVAL '15 days'
    ),
    (
        'PAP-GEN-004',
        NULL,
        'Foamy Azul',
        'Lamina de foamy para manualidades.',
        'Manualidades',
        NULL,
        12.00,
        6.00,
        25,
        TRUE,
        NOW() - INTERVAL '8 months',
        NOW() - INTERVAL '8 days'
    ),
    (
        'PAP-GEN-005',
        NULL,
        'Foamy Glitter Dorado',
        'Lamina de foamy con acabado brillante.',
        'Manualidades',
        NULL,
        18.00,
        9.00,
        15,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '20 days'
    ),
    (
        'PAP-GEN-006',
        NULL,
        'Papel Crepe Verde',
        'Papel crepe para manualidades y decoracion.',
        'Manualidades',
        NULL,
        10.00,
        4.50,
        20,
        TRUE,
        NOW() - INTERVAL '5 months',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-GEN-007',
        NULL,
        'Papel Crepe Rosa',
        'Papel crepe para manualidades y decoracion.',
        'Manualidades',
        NULL,
        10.00,
        4.50,
        20,
        TRUE,
        NOW() - INTERVAL '4 months',
        NOW() - INTERVAL '10 days'
    ),
    (
        'PAP-GEN-008',
        NULL,
        'Cartulina Negra',
        'Cartulina negra para trabajos escolares.',
        'Cartulina',
        NULL,
        9.00,
        4.00,
        30,
        TRUE,
        NOW() - INTERVAL '3 months',
        NOW() - INTERVAL '5 days'
    ),
    (
        'PAP-GEN-009',
        NULL,
        'Cartulina Amarilla',
        'Cartulina amarilla para trabajos escolares.',
        'Cartulina',
        NULL,
        9.00,
        4.00,
        30,
        TRUE,
        NOW() - INTERVAL '2 months',
        NOW() - INTERVAL '12 days'
    ),
    (
        'PAP-GEN-010',
        NULL,
        'Hojas de Colores Carta',
        'Paquete de hojas de colores para trabajos escolares.',
        'Papel',
        NULL,
        42.00,
        23.00,
        10,
        TRUE,
        NOW() - INTERVAL '1 month',
        NOW() - INTERVAL '5 days'
    ),
    -- PRODUCTOS ADICIONALES
    (
        'PAP-BIC-011',
        '7501234500084',
        'Boligrafo BIC Rojo',
        'Boligrafo de tinta roja.',
        'Escritura',
        'BIC',
        7.00,
        3.20,
        20,
        TRUE,
        NOW() - INTERVAL '25 months',
        NOW() - INTERVAL '10 days'
    ),
    (
        'PAP-BIC-012',
        '7501234500085',
        'Boligrafo BIC Verde',
        'Boligrafo de tinta verde.',
        'Escritura',
        'BIC',
        7.00,
        3.20,
        15,
        TRUE,
        NOW() - INTERVAL '21 months',
        NOW() - INTERVAL '3 months'
    ),
    (
        'PAP-PIL-011',
        '7501234500086',
        'Pluma Pilot G-2',
        'Pluma de gel para escritura.',
        'Escritura',
        'Pilot',
        42.00,
        23.00,
        10,
        TRUE,
        NOW() - INTERVAL '18 months',
        NOW() - INTERVAL '7 days'
    ),
    (
        'PAP-PEN-011',
        '7501234500087',
        'Pluma Pentel Gel',
        'Pluma de gel para escritura.',
        'Escritura',
        'Pentel',
        38.00,
        20.00,
        10,
        TRUE,
        NOW() - INTERVAL '15 months',
        NOW() - INTERVAL '15 days'
    ),
    (
        'PAP-FAB-041',
        '7501234500088',
        'Marcadores Faber-Castell 10 piezas',
        'Set de marcadores escolares de colores.',
        'Marcadores',
        'Faber-Castell',
        75.00,
        40.00,
        10,
        TRUE,
        NOW() - INTERVAL '12 months',
        NOW() - INTERVAL '4 days'
    ),
    (
        'PAP-PEL-031',
        '7501234500089',
        'Lapices de Colores Pelikan',
        'Caja de lapices de colores escolares.',
        'Colores',
        'Pelikan',
        55.00,
        29.00,
        10,
        TRUE,
        NOW() - INTERVAL '10 months',
        NOW() - INTERVAL '2 weeks'
    ),
    (
        'PAP-NOR-051',
        '7501234500090',
        'Libreta Norma',
        'Libreta para notas y escritura.',
        'Cuadernos',
        'Norma',
        35.00,
        18.00,
        15,
        TRUE,
        NOW() - INTERVAL '8 months',
        NOW() - INTERVAL '6 days'
    ),
    (
        'PAP-SCR-021',
        '7501234500091',
        'Cuaderno Scribe Raya',
        'Cuaderno escolar de rayas.',
        'Cuadernos',
        'Scribe',
        45.00,
        25.00,
        20,
        TRUE,
        NOW() - INTERVAL '6 months',
        NOW() - INTERVAL '1 month'
    ),
    (
        'PAP-VIN-021',
        '7501234500092',
        'Pinceles Vinci Escolares',
        'Set de pinceles para actividades artisticas.',
        'Pintura',
        'Vinci',
        62.00,
        32.00,
        8,
        TRUE,
        NOW() - INTERVAL '5 months',
        NOW() - INTERVAL '9 days'
    ),
    (
        'PAP-PEL-041',
        '7501234500093',
        'Acuarelas Pelikan 12 colores',
        'Set de acuarelas escolares de 12 colores.',
        'Pintura',
        'Pelikan',
        68.00,
        35.00,
        10,
        TRUE,
        NOW() - INTERVAL '4 months',
        NOW() - INTERVAL '3 days'
    ),
    (
        'PAP-MAP-021',
        '7501234500094',
        'Regla Maped 20 cm',
        'Regla plastica de 20 centimetros.',
        'Geometria',
        'Maped',
        14.00,
        7.00,
        20,
        TRUE,
        NOW() - INTERVAL '3 months',
        NOW() - INTERVAL '20 days'
    ),
    (
        'PAP-MAP-022',
        '7501234500095',
        'Tijeras Maped 16 cm',
        'Tijeras escolares de 16 centimetros.',
        'Corte',
        'Maped',
        55.00,
        29.00,
        10,
        TRUE,
        NOW() - INTERVAL '2 months',
        NOW() - INTERVAL '8 days'
    ),
    (
        'PAP-RES-011',
        '7501234500096',
        'Resistol Escolar 125 g',
        'Pegamento blanco para actividades escolares.',
        'Adhesivos',
        'Resistol',
        38.00,
        20.00,
        15,
        TRUE,
        NOW() - INTERVAL '45 days',
        NOW() - INTERVAL '5 days'
    ),
    (
        'PAP-PRI-021',
        '7501234500097',
        'Pritt 43 g',
        'Pegamento en barra de mayor capacidad.',
        'Adhesivos',
        'Pritt',
        68.00,
        36.00,
        10,
        TRUE,
        NOW() - INTERVAL '35 days',
        NOW() - INTERVAL '3 days'
    ),
    (
        'PAP-STA-041',
        '7501234500098',
        'Marcador Stabilo Azul',
        'Marcador de tinta azul.',
        'Marcadores',
        'Stabilo',
        25.00,
        13.00,
        15,
        TRUE,
        NOW() - INTERVAL '25 days',
        NOW() - INTERVAL '7 days'
    ),
    (
        'PAP-FAB-051',
        '7501234500099',
        'Lapiz Faber-Castell Rojo',
        'Lapiz de color rojo para actividades escolares.',
        'Colores',
        'Faber-Castell',
        9.50,
        4.80,
        20,
        TRUE,
        NOW() - INTERVAL '20 days',
        NOW() - INTERVAL '2 days'
    ),
    (
        'PAP-DIX-031',
        '7501234500100',
        'Colores Dixon 12 piezas',
        'Caja de lapices de colores para uso escolar.',
        'Colores',
        'Dixon',
        45.00,
        24.00,
        15,
        TRUE,
        NOW(),
        NOW()
    )

)
INSERT INTO
    "product" (
        "sku",
        "barcode",
        "name",
        "description",
        "category_id",
        "brand_id",
        "sale_price",
        "cost_price",
        "stock_alert_level",
        "active",
        "created_at",
        "updated_at"
    )
SELECT
    seed_products.sku,
    seed_products.barcode,
    seed_products.name,
    seed_products.description,
    category.id,
    brand.id,
    seed_products.sale_price,
    seed_products.cost_price,
    seed_products.stock_alert_level,
    seed_products.active,
    seed_products.created_at,
    seed_products.updated_at
FROM
    seed_products
INNER JOIN
    "category" AS category
    ON category.name = seed_products.category_name
LEFT JOIN
    "brand" AS brand
    ON brand.name = seed_products.brand_name
ON CONFLICT ("sku") DO NOTHING;